appversion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: {{.Values.recommendationService.replicaCount}}
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service

    spec:
      containers:
      - name: main
        image:"{{.Values.recommendationService.image.repository}} : {{.Values.recommendationService.image.tag}}"
        imagePullPolicay: {{.Values.recommendationService.image.pullPolicy}}
        ports:
        - containerPort: {{.Values.recommendationService.service.port}}
        resources:
          requests:
            cpu: {{ .Values.recommendationService.resources.requests.cpu }}
            memory: {{ .Values.recommendationService.resources.requests.memory }}
          limits:
            cpu: {{ .Values.recommendationService.resources.limits.cpu }}
            memory: {{ .Values.recommendationService.resources.limits.memory }}