{{- range $name, $config := .Values.services }}
{{- if $config.autoscaling }}
{{- if $config.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-hpa
  labels:
    {{- include "citrus-app.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $config.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $config.autoscaling.maxReplicas | default 3 }}
  metrics:
    {{- if $config.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetCPUUtilizationPercentage | default 80 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}