{{- range $name, $config := .Values.services }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: {{ $name }}-monitor
    labels:
        release: monitoring-stack
spec:
    selector:
        matchLabels:
            app: {{$name}}
    endpoints:
    - port: http
      interval: 15s
{{- end }}