global:
  domain: citrus.local
  environment: production

services:

  recommendationservice:
    replicaCount: 1
    image: {repository: ghcr.io/zihankuang/citrus-recommendation, tag: latest, pullPolicy: IfNotPresent }
    resources:
      limits: {cpu: 200m, memory: 256Mi}
      requests: { cpu: 100m, memory: 128Mi }
    service: {port: 80, targetPort: 8080 }

  frontend:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend, tag: v0.10.5, pullPolicy: IfNotPresent }
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50
    resources:
      limits: { cpu: 200m, memory: 256Mi }
      requests: { cpu: 100m, memory: 128Mi }
    service: { port: 80, targetPort: 8080, type: LoadBalancer }

  adservice:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice, tag: v0.10.5, pullPolicy: IfNotPresent }
    resources:
      limits: { cpu: 300m, memory: 512Mi }
      requests: { cpu: 100m, memory: 256Mi }
    service: { port: 9555, targetPort: 9555 }

  cartservice:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice, tag: v0.10.5, pullPolicy: IfNotPresent }
    resources:
      limits: { cpu: 200m, memory: 256Mi }
      requests: { cpu: 100m, memory: 128Mi }
    service: { port: 7070, targetPort: 7070 }

  checkoutservice:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice, tag: v0.10.5, pullPolicy: IfNotPresent }
    service: { port: 5050, targetPort: 5050 }
    resources:
      limits: { cpu: 200m, memory: 256Mi }
      requests: { cpu: 100m, memory: 128Mi }

  currencyservice:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice, tag: v0.10.5, pullPolicy: IfNotPresent }
    service: { port: 7000, targetPort: 7000 }
    resources:
      limits: { cpu: 200m, memory: 256Mi }
      requests: { cpu: 100m, memory: 128Mi }

  emailservice:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice, tag: v0.10.5, pullPolicy: IfNotPresent }
    service: { port: 8080, targetPort: 8080 }
    resources:
      limits: { cpu: 100m, memory: 128Mi }
      requests: { cpu: 50m, memory: 64Mi }

  paymentservice:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice, tag: v0.10.5, pullPolicy: IfNotPresent }
    service: { port: 50051, targetPort: 50051 }
    resources:
      limits: { cpu: 100m, memory: 128Mi }
      requests: { cpu: 50m, memory: 64Mi}

  productcatalogservice:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice, tag: v0.10.5, pullPolicy: IfNotPresent }
    service: { port: 3550, targetPort: 3550 }
    resources:
      limits: { cpu: 200m, memory: 256Mi }
      requests: { cpu: 100m, memory: 128Mi }

  shippingservice:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice, tag: v0.10.5, pullPolicy: IfNotPresent }
    service: { port: 50051, targetPort: 50051 }
    resources:
      limits: { cpu: 200m, memory: 256Mi }
      requests: { cpu: 100m, memory: 128Mi }

  shoppingassistantservice:
    replicaCount: 1
    image: { repository: ghcr.io/zihankuang/citrus-shoppingassistant, tag: latest, pullPolicy: IfNotPresent }
    service: { port: 8080, targetPort: 8080 }
    resources:
      limits: { cpu: 500m, memory: 512Mi }  
      requests: { cpu: 200m, memory: 256Mi }

  loadgenerator:
    replicaCount: 1
    image: { repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator, tag: v0.10.5, pullPolicy: IfNotPresent }
    service: { port: 8080, targetPort: 8080 }
    env:
      - name: FRONTEND_ADDR
        value: "frontend:80"
      - name: USERS
        value: "100"
    resources:
      limits: { cpu: 300m, memory: 512Mi }
      requests: { cpu: 100m, memory: 256Mi }